steps:
  #  using our ko builder we will build our application that lives in ./cmd/ko
  - name: 'node'
    id: install
    entrypoint: 'npm'
    args: ['install', 'web/']
  - name: 'node'
    id: run-build
    entrypoint: 'npm'
    args: ['--prefix', 'web/', 'run', 'build']
  - name: gcr.io/$PROJECT_ID/ko
    entrypoint: /bin/sh
    env:
      - 'KO_DOCKER_REPO=gcr.io/$PROJECT_ID'
    # we write the result of ko publish to a txt file so we can persist the variable between steps
    args:
      - -c
      - |
        echo $(/ko publish ./cmd/ping) > ./ko_container.txt || exit 1
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        [[ ! -z $_PR_NUMBER ]] && gcloud run deploy gcping-pr-${_PR_NUMBER} \
        --image=$(cat ./ko_container.txt) \
        --region=us-central1 \
        --platform=managed
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        [[ ! -z $_PR_NUMBER ]] && gcloud run services add-iam-policy-binding gcping-pr-${_PR_NUMBER} \
        --member="allUsers" \
        --role="roles/run.invoker"
        --region=us-central1